# Generated by Django 5.1.4 on 2024-12-30 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='orderdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Flavour', models.CharField(default='', max_length=50)),
                ('Weight', models.IntegerField(default='')),
                ('Quantity', models.IntegerField(default='')),
                ('Actual_Price', models.IntegerField(default='')),
                ('Discount', models.IntegerField(default='')),
                ('Discount_Price', models.IntegerField(default='')),
                ('Delivery_Address', models.CharField(default='', max_length=200)),
                ('Pincode', models.IntegerField(default='')),
                ('Mobile', models.IntegerField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='orderdata1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Flavour', models.CharField(default='', max_length=50)),
                ('Weight', models.IntegerField(default='')),
                ('Quantity', models.IntegerField(default='')),
                ('Actual_Price', models.IntegerField(default='')),
                ('Discount', models.IntegerField(default='')),
                ('Discount_Price', models.IntegerField(default='')),
                ('Delivery_Address', models.CharField(default='', max_length=200)),
                ('Pincode', models.IntegerField(default='')),
                ('Mobile', models.IntegerField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='orderdata2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Flavour', models.CharField(default='', max_length=50)),
                ('Weight', models.IntegerField(default='')),
                ('Quantity', models.IntegerField(default='')),
                ('Actual_Price', models.IntegerField(default='')),
                ('Discount', models.IntegerField(default='')),
                ('Discount_Price', models.IntegerField(default='')),
                ('Delivery_Address', models.CharField(default='', max_length=200)),
                ('Pincode', models.IntegerField(default='')),
                ('Mobile', models.IntegerField(default='')),
            ],
        ),
    ]
